version: '3.7'

services:
  elasticsearch:
    image: ghcr.io/tal-sitton/seret-search:latest
    pull_policy: always
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  vpn-proxy:
    build: .
    ports:
      - "8118:8118"
    privileged: true
    dns: "1.1.1.1"
    env_file: .env
