FROM elasticsearch:8.13.0

ENV discovery.type=single-node
ENV xpack.security.enabled=false

RUN bin/elasticsearch-plugin install --batch analysis-icu && \
    bin/elasticsearch-plugin install https://github.com/Sefaria/Sefaria-ElasticSearch/releases/download/v1.1.6/sefaria-naive-lemmatizer-v1.1.6.zip && \
    bin/elasticsearch-plugin install https://github.com/Sefaria/Sefaria-ElasticSearch/releases/download/v1.1.6/sefaria-naive-lemmatizer-less-prefixes-v1.1.6.zip

HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
  CMD curl -s -f http://localhost:9200/_cluster/health || exit 1