remote_theme: tuur29/pages-themes-cayman
title: Seret Indexer
description: "fetch movie data from seret.co.il and from edb.co.il and index it into Elasticsearch"
markdown: kramdown
url: https://code.sitton.dev
baseurl: /Seret-Indexer

color:
  gradient_left: "#001624"
  gradient_right: "#00d4ff"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

show_downloads: true
buttons:
  zip_hide: true
  tar_title: About me
  tar_url: /
  tar_hide: false
