name: run program

on:
  repository_dispatch:
    types: [ test ]

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "23 0 * * *" # 2:23am every day israel time (23:23 UTC time)

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: ghcr.io/tal-sitton/heb-elastic:latest
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: cp to container
        continue-on-error: true
        run: |
          docker cp esdata elasticsearch:/usr/share/elasticsearch/data

      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run program
        run:
          python main.py
        env:
          ELASTIC_HOST: http://localhost:9200

      - name: config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: add elastic-data
        run: |
          docker cp elasticsearch:/usr/share/elasticsearch/data esdata
          git add esdata

      - name: commit file and push
        run: |
          git commit -m "Update elastic-data"
          git push